export const CURRENCIES = [
  { label: "Nigerian Naira", value: "NGN" },
  { label: "US Dollar", value: "USD" },
  { label: "British Pound", value: "GBP" },
  { label: "Euro", value: "EUR" },
  { label: "Japanese Yen", value: "JPY" },
  { label: "Australian Dollar", value: "AUD" },
  { label: "Canadian Dollar", value: "CAD" },
  { label: "Swiss Franc", value: "CHF" },
  { label: "Chinese Yuan", value: "CNY" },
  { label: "New Zealand Dollar", value: "NZD" },
  { label: "Singapore Dollar", value: "SGD" },
  { label: "South African Rand", value: "ZAR" },
  { label: "Egyptian Pound", value: "EGP" },
  { label: "Kenyan Shilling", value: "KES" },
  { label: "Ghanaian Cedi", value: "GHS" },
  { label: "Moroccan Dirham", value: "MAD" },
  { label: "Ethiopian Birr", value: "ETB" },
  { label: "Angolan Kwanza", value: "AOA" },
];
