import type { SubscriptionProps } from "@/types";

export const SUBSCRIPTIONS: SubscriptionProps[] = [
  {
    id: "f9740084-cc47-402e-801e-3d3b72b7e888",
    name: "Free",
    description: "Get started with basic features",
    type: "monthly",
    tier: "free",
    price: 0,
    currency: "NGN",
    billing_cycle_days: 30,
    trial_period_days: 0,
    features: {
      analytics: true,
      basic_profile: true,
      custom_domain: false,
      job_applications: 5,
      premium_profile: false,
      priority_support: false,
      resume_downloads: "unlimited",
      verified_badge: false,
    },
    max_projects: 3,
    max_skills: 10,
    max_experiences: 5,
    is_active: true,
    is_popular: false,
    sort_order: 1,
    created_at: "2026-01-31T00:59:42.459536Z",
    updated_at: "2026-01-31T00:59:42.459536Z",
  },
  {
    id: "79cbec40-532b-4141-9198-a45b69c6ea7b",
    name: "Pro Monthly",
    description: "Unlock all features with monthly billing",
    type: "monthly",
    tier: "premium",
    price: 1200,
    currency: "NGN",
    billing_cycle_days: 30,
    trial_period_days: 7,
    features: {
      analytics: true,
      basic_profile: true,
      custom_domain: true,
      job_applications: "unlimited",
      premium_profile: true,
      priority_support: true,
      resume_downloads: "unlimited",
      verified_badge: true,
    },
    max_projects: 20,
    max_skills: 50,
    max_experiences: 20,
    is_active: true,
    is_popular: true,
    sort_order: 2,
    created_at: "2026-01-31T00:59:43.315323Z",
    updated_at: "2026-01-31T00:59:43.315323Z",
  },
  {
    id: "efd87476-324c-4a06-a927-a139ed344e89",
    name: "Pro Yearly",
    description: "Save 20% with annual billing",
    type: "yearly",
    tier: "premium",
    price: 11520,
    currency: "NGN",
    billing_cycle_days: 365,
    trial_period_days: 14,
    features: {
      analytics: true,
      basic_profile: true,
      custom_domain: true,
      job_applications: "unlimited",
      premium_profile: true,
      priority_support: true,
      resume_downloads: "unlimited",
      verified_badge: true,
    },
    max_projects: 20,
    max_skills: 50,
    max_experiences: 20,
    is_active: true,
    is_popular: false,
    sort_order: 3,
    created_at: "2026-01-31T00:59:43.995766Z",
    updated_at: "2026-01-31T00:59:43.995766Z",
  },
];
